//! Deliberately in-memory fixtures. This prototype never opens a repository.
#[derive(Clone)]
pub struct Commit {
    pub hash: &'static str,
    pub subject: &'static str,
    pub author: &'static str,
    pub time: &'static str,
    pub lane: usize,
    pub parents: &'static [usize],
    pub reference: &'static str,
    pub description: &'static str,
    pub file: usize,
}

pub const COMMITS: &[Commit] = &[
    Commit {
        hash: "e7a91c2",
        subject: "Give the repository room to breathe",
        author: "Anup Reddy",
        time: "12 min",
        lane: 0,
        parents: &[1],
        reference: "HEAD · main",
        description: "Refine the workspace spacing and bring the commit inspector closer to the history. Small details, a calmer workspace.",
        file: 0,
    },
    Commit {
        hash: "b48f0d1",
        subject: "Merge branch 'feature/graph'",
        author: "Anup Reddy",
        time: "38 min",
        lane: 0,
        parents: &[2, 4],
        reference: "origin/main",
        description: "Bring the new graph renderer into main, including stable lanes and clearer merge connections.",
        file: 1,
    },
    Commit {
        hash: "31c7a09",
        subject: "Keep selection when the repository refreshes",
        author: "Maya Chen",
        time: "1 hour",
        lane: 0,
        parents: &[3],
        reference: "",
        description: "Use stable commit identities to preserve the selected item across repository updates.",
        file: 2,
    },
    Commit {
        hash: "90be4f6",
        subject: "Add keyboard navigation to the sidebar",
        author: "Anup Reddy",
        time: "2 hours",
        lane: 0,
        parents: &[6],
        reference: "",
        description: "Move between workspaces without leaving the keyboard. Keep focus visible and predictable.",
        file: 0,
    },
    Commit {
        hash: "a28de43",
        subject: "Draw smooth connections between merge lanes",
        author: "Maya Chen",
        time: "3 hours",
        lane: 1,
        parents: &[5],
        reference: "feature/graph",
        description: "Paint curved connections between commits and their parents using the native graphics pipeline.",
        file: 1,
    },
    Commit {
        hash: "fd2108b",
        subject: "Preserve graph lanes across history pages",
        author: "Maya Chen",
        time: "4 hours",
        lane: 1,
        parents: &[6],
        reference: "",
        description: "Carry the active lane frontier into the next history page so scrolling does not rearrange the graph.",
        file: 1,
    },
    Commit {
        hash: "6dc4a80",
        subject: "Merge branch 'feature/themes'",
        author: "Anup Reddy",
        time: "Yesterday",
        lane: 0,
        parents: &[7, 9],
        reference: "v0.2.0",
        description: "Introduce a shared palette for surfaces, typography, and semantic Git colors.",
        file: 3,
    },
    Commit {
        hash: "732fb01",
        subject: "Separate working tree and index changes",
        author: "Anup Reddy",
        time: "Yesterday",
        lane: 0,
        parents: &[8],
        reference: "",
        description: "Represent staged and unstaged changes independently, including files that appear in both states.",
        file: 2,
    },
    Commit {
        hash: "8ea712f",
        subject: "Introduce the repository session",
        author: "Maya Chen",
        time: "Yesterday",
        lane: 0,
        parents: &[11],
        reference: "",
        description: "Create the application boundary for repository state and background activity.",
        file: 2,
    },
    Commit {
        hash: "c419ab0",
        subject: "A quieter palette for late-night commits",
        author: "Anup Reddy",
        time: "2 days",
        lane: 2,
        parents: &[10],
        reference: "feature/themes",
        description: "Balance low contrast surfaces with readable foregrounds and a restrained mint accent.",
        file: 3,
    },
    Commit {
        hash: "d0528c4",
        subject: "Define shared design tokens",
        author: "Anup Reddy",
        time: "2 days",
        lane: 2,
        parents: &[11],
        reference: "",
        description: "Collect the visual vocabulary in one place so every workspace feels part of the same application.",
        file: 3,
    },
    Commit {
        hash: "47bc81a",
        subject: "Scaffold the native workspace",
        author: "Anup Reddy",
        time: "3 days",
        lane: 0,
        parents: &[12],
        reference: "",
        description: "Lay the foundation for a desktop application written in Rust.",
        file: 4,
    },
    Commit {
        hash: "02f63e9",
        subject: "Start something good",
        author: "Anup Reddy",
        time: "3 days",
        lane: 0,
        parents: &[],
        reference: "",
        description: "The first commit. A small beginning for a more visual way to work with Git.",
        file: 4,
    },
];

pub struct FileChange {
    pub path: &'static str,
    pub status: &'static str,
    pub added: usize,
    pub removed: usize,
    pub staged: bool,
    pub patch: &'static [(&'static str, &'static str)],
}

pub fn files() -> Vec<FileChange> {
    vec![
        FileChange {
            path: "src/ui/workspace.rs",
            status: "M",
            added: 18,
            removed: 6,
            staged: false,
            patch: &[
                (" ", "impl Render for Workspace {"),
                (" ", "    fn render(&mut self, cx: &mut Context<Self>) {"),
                ("-", "        let spacing = px(12.0);"),
                ("+", "        let spacing = theme::SPACE_LG;"),
                (" ", "        div()"),
                (" ", "            .flex()"),
                ("+", "            .gap(spacing)"),
                ("+", "            .bg(theme::SURFACE)"),
                (" ", "            .child(self.history(cx))"),
                ("-", "            .child(self.details(cx))"),
                ("+", "            .child(self.inspector(cx))"),
                (" ", "    }"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/graph/renderer.rs",
            status: "M",
            added: 42,
            removed: 12,
            staged: true,
            patch: &[
                (" ", "fn paint_edge(edge: &Edge, window: &mut Window) {"),
                ("-", "    path.line_to(edge.end);"),
                ("+", "    let midpoint = (edge.start.y + edge.end.y) / 2.0;"),
                ("+", "    path.cubic_bezier_to("),
                ("+", "        edge.end,"),
                ("+", "        point(edge.start.x, midpoint),"),
                ("+", "        point(edge.end.x, midpoint),"),
                ("+", "    );"),
                (" ", "    window.paint_path(path, edge.color);"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/core/session.rs",
            status: "M",
            added: 24,
            removed: 8,
            staged: false,
            patch: &[
                (" ", "pub struct RepositorySession {"),
                (" ", "    pub repository: RepositoryId,"),
                ("-", "    pub snapshot: Snapshot,"),
                ("+", "    pub worktree: WorktreeId,"),
                ("+", "    pub generation: u64,"),
                ("+", "    pub selected_commit: Option<ObjectId>,"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/ui/theme.rs",
            status: "A",
            added: 36,
            removed: 0,
            staged: true,
            patch: &[
                ("+", "pub const SURFACE: u32 = 0x15191e;"),
                ("+", "pub const FOREGROUND: u32 = 0xe4e8e7;"),
                ("+", "pub const ACCENT: u32 = 0x87d5b0;"),
                ("+", "pub const SPACE_LG: Pixels = px(24.0);"),
                ("+", ""),
                ("+", "// A shared vocabulary for every workspace."),
            ],
        },
        FileChange {
            path: "docs/design-notes.md",
            status: "?",
            added: 12,
            removed: 0,
            staged: false,
            patch: &[
                ("+", "# A little more clarity"),
                ("+", ""),
                ("+", "A repository is a story, not just a list of commits."),
                ("+", "Keep the relationships visible."),
                ("+", "Give each operation a clear beginning and end."),
            ],
        },
    ]
}
