//! Deliberately in-memory fixtures. This prototype never opens a repository.
#[derive(Clone)]
pub struct Commit {
    pub hash: &'static str,
    pub subject: &'static str,
    pub author: &'static str,
    pub time: &'static str,
    pub parents: &'static [usize],
    /// The branch this commit sits on. Lanes are derived from the branch
    /// selection at render time rather than stored here.
    pub branch: &'static str,
    pub reference: &'static str,
    pub description: &'static str,
    pub file: usize,
}

pub const COMMITS: &[Commit] = &[
    Commit {
        hash: "e7a91c2",
        subject: "Give the repository room to breathe",
        author: "Anup Reddy",
        time: "12 min",
        branch: "main",
        parents: &[3],
        reference: "",
        description: "Refine the workspace spacing and bring the commit inspector closer to the history.",
        file: 0,
    },
    Commit {
        hash: "4b2d8f1",
        subject: "Handle renamed entries in porcelain v2",
        author: "Iris Okafor",
        time: "40 min",
        branch: "fix/status-parse",
        parents: &[2],
        reference: "",
        description: "Parse the rename score and both paths instead of dropping the entry.",
        file: 2,
    },
    Commit {
        hash: "9c1e07a",
        subject: "Add a failing case for unmerged paths",
        author: "Iris Okafor",
        time: "1 hour",
        branch: "fix/status-parse",
        parents: &[7],
        reference: "",
        description: "Cover the conflict states before changing the parser.",
        file: 2,
    },
    Commit {
        hash: "b48f0d1",
        subject: "Merge branch 'feature/graph'",
        author: "Anup Reddy",
        time: "2 hours",
        branch: "main",
        parents: &[7, 4],
        reference: "origin/main",
        description: "Bring the new graph renderer into main, including stable lanes.",
        file: 1,
    },
    Commit {
        hash: "a28de43",
        subject: "Draw connectors with square corners",
        author: "Maya Chen",
        time: "3 hours",
        branch: "feature/graph",
        parents: &[5],
        reference: "",
        description: "Replace the long cubic sweeps with a horizontal run and small corners.",
        file: 1,
    },
    Commit {
        hash: "fd2108b",
        subject: "Preserve graph lanes across history pages",
        author: "Maya Chen",
        time: "4 hours",
        branch: "feature/graph",
        parents: &[6],
        reference: "",
        description: "Carry the active lane frontier into the next page so scrolling is stable.",
        file: 1,
    },
    Commit {
        hash: "7e3c5a9",
        subject: "Lay out commit lanes from the parent walk",
        author: "Maya Chen",
        time: "5 hours",
        branch: "feature/graph",
        parents: &[12],
        reference: "",
        description: "Derive lanes from topology instead of storing them on each commit.",
        file: 1,
    },
    Commit {
        hash: "31c7a09",
        subject: "Keep selection when the repository refreshes",
        author: "Tomas Lind",
        time: "6 hours",
        branch: "main",
        parents: &[9],
        reference: "",
        description: "Use stable commit identities to preserve the selected item.",
        file: 2,
    },
    Commit {
        hash: "c0f4b72",
        subject: "Pin the release checklist for 0.3",
        author: "Anup Reddy",
        time: "8 hours",
        branch: "release/0.3",
        parents: &[9],
        reference: "",
        description: "Freeze the scope and record what still blocks the release.",
        file: 4,
    },
    Commit {
        hash: "6dc4a80",
        subject: "Merge branch 'feature/themes'",
        author: "Anup Reddy",
        time: "Yesterday",
        branch: "main",
        parents: &[12, 10],
        reference: "v0.3.0",
        description: "Introduce a shared palette for surfaces, typography, and semantic colors.",
        file: 3,
    },
    Commit {
        hash: "c419ab0",
        subject: "A quieter palette for late-night commits",
        author: "Priya Nair",
        time: "Yesterday",
        branch: "feature/themes",
        parents: &[11],
        reference: "",
        description: "Balance low contrast surfaces with readable foregrounds.",
        file: 3,
    },
    Commit {
        hash: "d0528c4",
        subject: "Define shared design tokens",
        author: "Priya Nair",
        time: "Yesterday",
        branch: "feature/themes",
        parents: &[18],
        reference: "",
        description: "Collect the visual vocabulary in one place.",
        file: 3,
    },
    Commit {
        hash: "732fb01",
        subject: "Separate working tree and index changes",
        author: "Tomas Lind",
        time: "2 days",
        branch: "main",
        parents: &[15],
        reference: "",
        description: "Represent staged and unstaged changes independently.",
        file: 2,
    },
    Commit {
        hash: "5a9d13e",
        subject: "Try a virtualized history list",
        author: "Maya Chen",
        time: "2 days",
        branch: "experiment/gpui",
        parents: &[14],
        reference: "",
        description: "Only build rows for the visible window and measure the difference.",
        file: 1,
    },
    Commit {
        hash: "8f207bc",
        subject: "Spike: measure paint cost per row",
        author: "Maya Chen",
        time: "2 days",
        branch: "experiment/gpui",
        parents: &[18],
        reference: "",
        description: "Instrument the paint phase before optimizing anything.",
        file: 1,
    },
    Commit {
        hash: "1e6b4d0",
        subject: "Merge branch 'feature/search'",
        author: "Anup Reddy",
        time: "3 days",
        branch: "main",
        parents: &[18, 16],
        reference: "v0.2.0",
        description: "Search across message, author, hash, branch, and tag.",
        file: 0,
    },
    Commit {
        hash: "aa73f52",
        subject: "Match commits by author and hash",
        author: "Iris Okafor",
        time: "3 days",
        branch: "feature/search",
        parents: &[17],
        reference: "",
        description: "Extend the filter beyond the subject line.",
        file: 0,
    },
    Commit {
        hash: "3bd9e81",
        subject: "Add the filter field to the history",
        author: "Iris Okafor",
        time: "4 days",
        branch: "feature/search",
        parents: &[20],
        reference: "",
        description: "A single field that narrows the visible commits as you type.",
        file: 0,
    },
    Commit {
        hash: "8ea712f",
        subject: "Introduce the repository session",
        author: "Tomas Lind",
        time: "4 days",
        branch: "main",
        parents: &[20],
        reference: "",
        description: "Create the boundary for repository state and background activity.",
        file: 2,
    },
    Commit {
        hash: "f61c208",
        subject: "Start the contributor handbook",
        author: "Priya Nair",
        time: "5 days",
        branch: "docs/handbook",
        parents: &[20],
        reference: "",
        description: "Explain the architecture before the interface grows further.",
        file: 4,
    },
    Commit {
        hash: "47bc81a",
        subject: "Scaffold the native workspace",
        author: "Anup Reddy",
        time: "6 days",
        branch: "main",
        parents: &[21],
        reference: "",
        description: "The first window, the first panel, and a place to put everything else.",
        file: 1,
    },
    Commit {
        hash: "02f63e9",
        subject: "Initial commit",
        author: "Anup Reddy",
        time: "6 days",
        branch: "main",
        parents: &[],
        reference: "",
        description: "A small beginning for a more visual way to work with Git.",
        file: 4,
    },
];

pub struct FileChange {
    pub path: &'static str,
    pub status: &'static str,
    pub added: usize,
    pub removed: usize,
    pub staged: bool,
    pub patch: &'static [(&'static str, &'static str)],
}

pub fn files() -> Vec<FileChange> {
    vec![
        FileChange {
            path: "src/ui/workspace.rs",
            status: "M",
            added: 18,
            removed: 6,
            staged: false,
            patch: &[
                (" ", "impl Render for Workspace {"),
                (" ", "    fn render(&mut self, cx: &mut Context<Self>) {"),
                ("-", "        let spacing = px(12.0);"),
                ("+", "        let spacing = theme::SPACE_LG;"),
                (" ", "        div()"),
                (" ", "            .flex()"),
                ("+", "            .gap(spacing)"),
                ("+", "            .bg(theme::SURFACE)"),
                (" ", "            .child(self.history(cx))"),
                ("-", "            .child(self.details(cx))"),
                ("+", "            .child(self.inspector(cx))"),
                (" ", "    }"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/graph/renderer.rs",
            status: "M",
            added: 42,
            removed: 12,
            staged: true,
            patch: &[
                (" ", "fn paint_edge(edge: &Edge, window: &mut Window) {"),
                ("-", "    path.line_to(edge.end);"),
                ("+", "    let midpoint = (edge.start.y + edge.end.y) / 2.0;"),
                ("+", "    path.cubic_bezier_to("),
                ("+", "        edge.end,"),
                ("+", "        point(edge.start.x, midpoint),"),
                ("+", "        point(edge.end.x, midpoint),"),
                ("+", "    );"),
                (" ", "    window.paint_path(path, edge.color);"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/core/session.rs",
            status: "M",
            added: 24,
            removed: 8,
            staged: false,
            patch: &[
                (" ", "pub struct RepositorySession {"),
                (" ", "    pub repository: RepositoryId,"),
                ("-", "    pub snapshot: Snapshot,"),
                ("+", "    pub worktree: WorktreeId,"),
                ("+", "    pub generation: u64,"),
                ("+", "    pub selected_commit: Option<ObjectId>,"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/ui/theme.rs",
            status: "A",
            added: 36,
            removed: 0,
            staged: true,
            patch: &[
                ("+", "pub const SURFACE: u32 = 0x15191e;"),
                ("+", "pub const FOREGROUND: u32 = 0xe4e8e7;"),
                ("+", "pub const ACCENT: u32 = 0x87d5b0;"),
                ("+", "pub const SPACE_LG: Pixels = px(24.0);"),
                ("+", ""),
                ("+", "// A shared vocabulary for every workspace."),
            ],
        },
        FileChange {
            path: "docs/design-notes.md",
            status: "?",
            added: 12,
            removed: 0,
            staged: false,
            patch: &[
                ("+", "# A little more clarity"),
                ("+", ""),
                ("+", "A repository is a story, not just a list of commits."),
                ("+", "Keep the relationships visible."),
                ("+", "Give each operation a clear beginning and end."),
            ],
        },
    ]
}

/// One row of the source tree. `depth` drives indentation, and a collapsed
/// directory hides every following entry until the depth returns to its own.
pub struct TreeEntry {
    pub depth: usize,
    pub name: &'static str,
    pub path: &'static str,
    pub directory: bool,
}

pub const TREE: &[TreeEntry] = &[
    TreeEntry {
        depth: 0,
        name: "src",
        path: "src",
        directory: true,
    },
    TreeEntry {
        depth: 1,
        name: "ui",
        path: "src/ui",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "workspace.rs",
        path: "src/ui/workspace.rs",
        directory: false,
    },
    TreeEntry {
        depth: 2,
        name: "theme.rs",
        path: "src/ui/theme.rs",
        directory: false,
    },
    TreeEntry {
        depth: 1,
        name: "graph",
        path: "src/graph",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "renderer.rs",
        path: "src/graph/renderer.rs",
        directory: false,
    },
    TreeEntry {
        depth: 1,
        name: "core",
        path: "src/core",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "session.rs",
        path: "src/core/session.rs",
        directory: false,
    },
    TreeEntry {
        depth: 0,
        name: "docs",
        path: "docs",
        directory: true,
    },
    TreeEntry {
        depth: 1,
        name: "design-notes.md",
        path: "docs/design-notes.md",
        directory: false,
    },
];

/// Fictional file contents for the source tabs.
pub fn source(path: &str) -> &'static [&'static str] {
    match path {
        "src/ui/workspace.rs" => &[
            "use gpui::{Context, IntoElement, Render};",
            "use crate::{graph::HistoryGraph, theme::Theme};",
            "",
            "pub struct Workspace {",
            "    graph: HistoryGraph,",
            "    theme: Theme,",
            "    selected_commit: usize,",
            "}",
            "",
            "impl Render for Workspace {",
            "    fn render(&mut self, cx: &mut Context<Self>) -> impl IntoElement {",
            "        let colors = self.theme.palette();",
            "",
            "        workspace_shell(colors)",
            "            .left(self.graph.render(cx))",
            "            .center(self.diff_editor(cx))",
            "            .right(self.repository_state(cx))",
            "    }",
            "}",
            "",
            "// The interface is native Rust and all data is still fictional.",
        ],
        "src/ui/theme.rs" => &[
            "//! A shared vocabulary for every workspace surface.",
            "",
            "pub const SURFACE: u32 = 0x15191e;",
            "pub const FOREGROUND: u32 = 0xe4e8e7;",
            "pub const ACCENT: u32 = 0x87d5b0;",
            "",
            "#[derive(Clone, Copy, PartialEq, Eq)]",
            "pub enum Theme {",
            "    Dark,",
            "    Light,",
            "}",
            "",
            "impl Theme {",
            "    pub fn palette(self) -> Palette {",
            "        match self {",
            "            Self::Dark => DARK,",
            "            Self::Light => LIGHT,",
            "        }",
            "    }",
            "}",
        ],
        "src/graph/renderer.rs" => &[
            "use gpui::{PathBuilder, Window, point, px};",
            "",
            "/// Paints one connector between a commit and a parent.",
            "pub fn paint_edge(edge: &Edge, window: &mut Window) {",
            "    let mut path = PathBuilder::stroke(px(2.));",
            "    path.move_to(edge.start);",
            "",
            "    if edge.start.x == edge.end.x {",
            "        path.line_to(edge.end);",
            "    } else {",
            "        // A horizontal run with small corners, never a long sweep.",
            "        path.line_to(edge.corner_in);",
            "        path.curve_to(edge.turn_in, edge.pivot_in);",
            "        path.line_to(edge.turn_out);",
            "        path.curve_to(edge.corner_out, edge.pivot_out);",
            "        path.line_to(edge.end);",
            "    }",
            "",
            "    window.paint_path(path, edge.color);",
            "}",
        ],
        "src/core/session.rs" => &[
            "use crate::{ObjectId, RepositoryId, WorktreeId};",
            "",
            "/// The boundary between the interface and a real repository.",
            "pub struct RepositorySession {",
            "    pub repository: RepositoryId,",
            "    pub worktree: WorktreeId,",
            "    pub generation: u64,",
            "    pub selected_commit: Option<ObjectId>,",
            "}",
            "",
            "impl RepositorySession {",
            "    /// Git work must never run on the UI thread.",
            "    pub async fn refresh(&mut self) -> Result<Snapshot> {",
            "        let snapshot = self.spawn_git(&[\"status\", \"--porcelain=v2\"]).await?;",
            "        self.generation += 1;",
            "        Ok(snapshot)",
            "    }",
            "}",
        ],
        "docs/design-notes.md" => &[
            "# A little more clarity",
            "",
            "A repository is a story, not just a list of commits.",
            "Keep the relationships visible.",
            "Give each operation a clear beginning and end.",
            "",
            "## Graph",
            "",
            "Every active branch keeps a straight vertical rail.",
            "Lane changes use a horizontal connector with small corners,",
            "so the eye follows a line instead of a curve.",
            "",
            "## Typography",
            "",
            "The editor uses the same monospace measure throughout,",
            "so diffs and sources line up column for column.",
        ],
        _ => &["// This file is part of the in-memory preview fixture.", ""],
    }
}

/// Every branch in the fixture, in the order lanes are handed out. The first
/// [`LANE_CAPACITY`](crate::graph::LANE_CAPACITY) are shown by default.
pub const BRANCHES: &[&str] = &[
    "main",
    "feature/graph",
    "feature/themes",
    "feature/search",
    "fix/status-parse",
    "release/0.3",
    "experiment/gpui",
    "docs/handbook",
];

/// The checked-out branch, and the commit it points at.
pub const HEAD_BRANCH: &str = "main";
pub const HEAD_COMMIT: usize = 0;

#[derive(Clone, Copy, PartialEq, Eq)]
pub enum RefKind {
    Local,
    Remote,
    Tag,
}

pub struct Reference {
    pub name: &'static str,
    pub kind: RefKind,
    pub commit: usize,
}

/// Every ref in the fixture, for the repository state panel.
pub const REFS: &[Reference] = &[
    Reference {
        name: "main",
        kind: RefKind::Local,
        commit: 0,
    },
    Reference {
        name: "fix/status-parse",
        kind: RefKind::Local,
        commit: 1,
    },
    Reference {
        name: "feature/graph",
        kind: RefKind::Local,
        commit: 4,
    },
    Reference {
        name: "release/0.3",
        kind: RefKind::Local,
        commit: 8,
    },
    Reference {
        name: "feature/themes",
        kind: RefKind::Local,
        commit: 10,
    },
    Reference {
        name: "experiment/gpui",
        kind: RefKind::Local,
        commit: 13,
    },
    Reference {
        name: "feature/search",
        kind: RefKind::Local,
        commit: 16,
    },
    Reference {
        name: "docs/handbook",
        kind: RefKind::Local,
        commit: 19,
    },
    Reference {
        name: "origin/main",
        kind: RefKind::Remote,
        commit: 3,
    },
    Reference {
        name: "v0.3.0",
        kind: RefKind::Tag,
        commit: 9,
    },
    Reference {
        name: "v0.2.0",
        kind: RefKind::Tag,
        commit: 15,
    },
];
