//! Deliberately in-memory fixtures. This prototype never opens a repository.
#[derive(Clone)]
pub struct Commit {
    pub hash: &'static str,
    pub subject: &'static str,
    pub author: &'static str,
    pub time: &'static str,
    pub lane: usize,
    pub parents: &'static [usize],
    /// The branch this commit sits on. Always rendered beside the hash.
    pub branch: &'static str,
    pub reference: &'static str,
    pub description: &'static str,
    pub file: usize,
}

pub const COMMITS: &[Commit] = &[
    Commit {
        hash: "e7a91c2",
        subject: "Give the repository room to breathe",
        author: "Anup Reddy",
        time: "12 min",
        lane: 0,
        parents: &[1],
        branch: "main",
        reference: "HEAD",
        description: "Refine the workspace spacing and bring the commit inspector closer to the history. Small details, a calmer workspace.",
        file: 0,
    },
    Commit {
        hash: "b48f0d1",
        subject: "Merge branch 'feature/graph'",
        author: "Anup Reddy",
        time: "38 min",
        lane: 0,
        parents: &[2, 4],
        branch: "main",
        reference: "origin/main",
        description: "Bring the new graph renderer into main, including stable lanes and clearer merge connections.",
        file: 1,
    },
    Commit {
        hash: "31c7a09",
        subject: "Keep selection when the repository refreshes",
        author: "Maya Chen",
        time: "1 hour",
        lane: 0,
        parents: &[3],
        branch: "main",
        reference: "",
        description: "Use stable commit identities to preserve the selected item across repository updates.",
        file: 2,
    },
    Commit {
        hash: "90be4f6",
        subject: "Add keyboard navigation to the sidebar",
        author: "Anup Reddy",
        time: "2 hours",
        lane: 0,
        parents: &[6],
        branch: "main",
        reference: "",
        description: "Move between workspaces without leaving the keyboard. Keep focus visible and predictable.",
        file: 0,
    },
    Commit {
        hash: "a28de43",
        subject: "Draw smooth connections between merge lanes",
        author: "Maya Chen",
        time: "3 hours",
        lane: 1,
        parents: &[5],
        branch: "feature/graph",
        reference: "",
        description: "Paint curved connections between commits and their parents using the native graphics pipeline.",
        file: 1,
    },
    Commit {
        hash: "fd2108b",
        subject: "Preserve graph lanes across history pages",
        author: "Maya Chen",
        time: "4 hours",
        lane: 1,
        parents: &[6],
        branch: "feature/graph",
        reference: "",
        description: "Carry the active lane frontier into the next history page so scrolling does not rearrange the graph.",
        file: 1,
    },
    Commit {
        hash: "6dc4a80",
        subject: "Merge branch 'feature/themes'",
        author: "Anup Reddy",
        time: "Yesterday",
        lane: 0,
        parents: &[7, 9],
        branch: "main",
        reference: "v0.2.0",
        description: "Introduce a shared palette for surfaces, typography, and semantic Git colors.",
        file: 3,
    },
    Commit {
        hash: "732fb01",
        subject: "Separate working tree and index changes",
        author: "Anup Reddy",
        time: "Yesterday",
        lane: 0,
        parents: &[8],
        branch: "main",
        reference: "",
        description: "Represent staged and unstaged changes independently, including files that appear in both states.",
        file: 2,
    },
    Commit {
        hash: "8ea712f",
        subject: "Introduce the repository session",
        author: "Maya Chen",
        time: "Yesterday",
        lane: 0,
        parents: &[11],
        branch: "main",
        reference: "",
        description: "Create the application boundary for repository state and background activity.",
        file: 2,
    },
    Commit {
        hash: "c419ab0",
        subject: "A quieter palette for late-night commits",
        author: "Anup Reddy",
        time: "2 days",
        lane: 2,
        parents: &[10],
        branch: "feature/themes",
        reference: "",
        description: "Balance low contrast surfaces with readable foregrounds and a restrained mint accent.",
        file: 3,
    },
    Commit {
        hash: "d0528c4",
        subject: "Define shared design tokens",
        author: "Anup Reddy",
        time: "2 days",
        lane: 2,
        parents: &[11],
        branch: "feature/themes",
        reference: "",
        description: "Collect the visual vocabulary in one place so every workspace feels part of the same application.",
        file: 3,
    },
    Commit {
        hash: "47bc81a",
        subject: "Scaffold the native workspace",
        author: "Anup Reddy",
        time: "3 days",
        lane: 0,
        parents: &[12],
        branch: "main",
        reference: "",
        description: "Lay the foundation for a desktop application written in Rust.",
        file: 4,
    },
    Commit {
        hash: "02f63e9",
        subject: "Start something good",
        author: "Anup Reddy",
        time: "3 days",
        lane: 0,
        parents: &[],
        branch: "main",
        reference: "",
        description: "The first commit. A small beginning for a more visual way to work with Git.",
        file: 4,
    },
];

pub struct FileChange {
    pub path: &'static str,
    pub status: &'static str,
    pub added: usize,
    pub removed: usize,
    pub staged: bool,
    pub patch: &'static [(&'static str, &'static str)],
}

pub fn files() -> Vec<FileChange> {
    vec![
        FileChange {
            path: "src/ui/workspace.rs",
            status: "M",
            added: 18,
            removed: 6,
            staged: false,
            patch: &[
                (" ", "impl Render for Workspace {"),
                (" ", "    fn render(&mut self, cx: &mut Context<Self>) {"),
                ("-", "        let spacing = px(12.0);"),
                ("+", "        let spacing = theme::SPACE_LG;"),
                (" ", "        div()"),
                (" ", "            .flex()"),
                ("+", "            .gap(spacing)"),
                ("+", "            .bg(theme::SURFACE)"),
                (" ", "            .child(self.history(cx))"),
                ("-", "            .child(self.details(cx))"),
                ("+", "            .child(self.inspector(cx))"),
                (" ", "    }"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/graph/renderer.rs",
            status: "M",
            added: 42,
            removed: 12,
            staged: true,
            patch: &[
                (" ", "fn paint_edge(edge: &Edge, window: &mut Window) {"),
                ("-", "    path.line_to(edge.end);"),
                ("+", "    let midpoint = (edge.start.y + edge.end.y) / 2.0;"),
                ("+", "    path.cubic_bezier_to("),
                ("+", "        edge.end,"),
                ("+", "        point(edge.start.x, midpoint),"),
                ("+", "        point(edge.end.x, midpoint),"),
                ("+", "    );"),
                (" ", "    window.paint_path(path, edge.color);"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/core/session.rs",
            status: "M",
            added: 24,
            removed: 8,
            staged: false,
            patch: &[
                (" ", "pub struct RepositorySession {"),
                (" ", "    pub repository: RepositoryId,"),
                ("-", "    pub snapshot: Snapshot,"),
                ("+", "    pub worktree: WorktreeId,"),
                ("+", "    pub generation: u64,"),
                ("+", "    pub selected_commit: Option<ObjectId>,"),
                (" ", "}"),
            ],
        },
        FileChange {
            path: "src/ui/theme.rs",
            status: "A",
            added: 36,
            removed: 0,
            staged: true,
            patch: &[
                ("+", "pub const SURFACE: u32 = 0x15191e;"),
                ("+", "pub const FOREGROUND: u32 = 0xe4e8e7;"),
                ("+", "pub const ACCENT: u32 = 0x87d5b0;"),
                ("+", "pub const SPACE_LG: Pixels = px(24.0);"),
                ("+", ""),
                ("+", "// A shared vocabulary for every workspace."),
            ],
        },
        FileChange {
            path: "docs/design-notes.md",
            status: "?",
            added: 12,
            removed: 0,
            staged: false,
            patch: &[
                ("+", "# A little more clarity"),
                ("+", ""),
                ("+", "A repository is a story, not just a list of commits."),
                ("+", "Keep the relationships visible."),
                ("+", "Give each operation a clear beginning and end."),
            ],
        },
    ]
}

/// One row of the source tree. `depth` drives indentation, and a collapsed
/// directory hides every following entry until the depth returns to its own.
pub struct TreeEntry {
    pub depth: usize,
    pub name: &'static str,
    pub path: &'static str,
    pub directory: bool,
}

pub const TREE: &[TreeEntry] = &[
    TreeEntry {
        depth: 0,
        name: "src",
        path: "src",
        directory: true,
    },
    TreeEntry {
        depth: 1,
        name: "ui",
        path: "src/ui",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "workspace.rs",
        path: "src/ui/workspace.rs",
        directory: false,
    },
    TreeEntry {
        depth: 2,
        name: "theme.rs",
        path: "src/ui/theme.rs",
        directory: false,
    },
    TreeEntry {
        depth: 1,
        name: "graph",
        path: "src/graph",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "renderer.rs",
        path: "src/graph/renderer.rs",
        directory: false,
    },
    TreeEntry {
        depth: 1,
        name: "core",
        path: "src/core",
        directory: true,
    },
    TreeEntry {
        depth: 2,
        name: "session.rs",
        path: "src/core/session.rs",
        directory: false,
    },
    TreeEntry {
        depth: 0,
        name: "docs",
        path: "docs",
        directory: true,
    },
    TreeEntry {
        depth: 1,
        name: "design-notes.md",
        path: "docs/design-notes.md",
        directory: false,
    },
];

/// Fictional file contents for the source tabs.
pub fn source(path: &str) -> &'static [&'static str] {
    match path {
        "src/ui/workspace.rs" => &[
            "use gpui::{Context, IntoElement, Render};",
            "use crate::{graph::HistoryGraph, theme::Theme};",
            "",
            "pub struct Workspace {",
            "    graph: HistoryGraph,",
            "    theme: Theme,",
            "    selected_commit: usize,",
            "}",
            "",
            "impl Render for Workspace {",
            "    fn render(&mut self, cx: &mut Context<Self>) -> impl IntoElement {",
            "        let colors = self.theme.palette();",
            "",
            "        workspace_shell(colors)",
            "            .left(self.graph.render(cx))",
            "            .center(self.diff_editor(cx))",
            "            .right(self.repository_state(cx))",
            "    }",
            "}",
            "",
            "// The interface is native Rust and all data is still fictional.",
        ],
        "src/ui/theme.rs" => &[
            "//! A shared vocabulary for every workspace surface.",
            "",
            "pub const SURFACE: u32 = 0x15191e;",
            "pub const FOREGROUND: u32 = 0xe4e8e7;",
            "pub const ACCENT: u32 = 0x87d5b0;",
            "",
            "#[derive(Clone, Copy, PartialEq, Eq)]",
            "pub enum Theme {",
            "    Dark,",
            "    Light,",
            "}",
            "",
            "impl Theme {",
            "    pub fn palette(self) -> Palette {",
            "        match self {",
            "            Self::Dark => DARK,",
            "            Self::Light => LIGHT,",
            "        }",
            "    }",
            "}",
        ],
        "src/graph/renderer.rs" => &[
            "use gpui::{PathBuilder, Window, point, px};",
            "",
            "/// Paints one connector between a commit and a parent.",
            "pub fn paint_edge(edge: &Edge, window: &mut Window) {",
            "    let mut path = PathBuilder::stroke(px(2.));",
            "    path.move_to(edge.start);",
            "",
            "    if edge.start.x == edge.end.x {",
            "        path.line_to(edge.end);",
            "    } else {",
            "        // A horizontal run with small corners, never a long sweep.",
            "        path.line_to(edge.corner_in);",
            "        path.curve_to(edge.turn_in, edge.pivot_in);",
            "        path.line_to(edge.turn_out);",
            "        path.curve_to(edge.corner_out, edge.pivot_out);",
            "        path.line_to(edge.end);",
            "    }",
            "",
            "    window.paint_path(path, edge.color);",
            "}",
        ],
        "src/core/session.rs" => &[
            "use crate::{ObjectId, RepositoryId, WorktreeId};",
            "",
            "/// The boundary between the interface and a real repository.",
            "pub struct RepositorySession {",
            "    pub repository: RepositoryId,",
            "    pub worktree: WorktreeId,",
            "    pub generation: u64,",
            "    pub selected_commit: Option<ObjectId>,",
            "}",
            "",
            "impl RepositorySession {",
            "    /// Git work must never run on the UI thread.",
            "    pub async fn refresh(&mut self) -> Result<Snapshot> {",
            "        let snapshot = self.spawn_git(&[\"status\", \"--porcelain=v2\"]).await?;",
            "        self.generation += 1;",
            "        Ok(snapshot)",
            "    }",
            "}",
        ],
        "docs/design-notes.md" => &[
            "# A little more clarity",
            "",
            "A repository is a story, not just a list of commits.",
            "Keep the relationships visible.",
            "Give each operation a clear beginning and end.",
            "",
            "## Graph",
            "",
            "Every active branch keeps a straight vertical rail.",
            "Lane changes use a horizontal connector with small corners,",
            "so the eye follows a line instead of a curve.",
            "",
            "## Typography",
            "",
            "The editor uses the same monospace measure throughout,",
            "so diffs and sources line up column for column.",
        ],
        _ => &["// This file is part of the in-memory preview fixture.", ""],
    }
}
